services:
  # Backend Service
  - type: web
    name: yatsya-backend
    plan: free
    env: node
    rootDir: server
    buildCommand: npm install && npm run build && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yatsya-db
          property: connectionString
      - key: PORT
        value: 5000
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

  # Frontend Service (Next.js)
  - type: web
    name: yatsya-frontend
    plan: free
    env: node
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: yatsya-backend
          property: url


databases:
  - name: yatsya-db
    plan: free
